"""Application-layer port contracts."""

from __future__ import annotations

from typing import Protocol


class CrawlRepositoryPort(Protocol):
    def save_crawl(self, crawl): ...
    def update_crawl(self, crawl): ...
    def get_crawl(self, crawl_id): ...
    def find_recent_crawl(self): ...


class CrawlDataRepositoryPort(Protocol):
    def save_page(self, page): ...
    def save_links(self, page_id, links): ...
    def save_headings(self, page_id, headings): ...
    def save_redirect(self, redirect): ...
    def load_analysis_data(self, crawl_id): ...


class AnalysisRepositoryPort(Protocol):
    def save_issues(self, crawl_id, issues): ...
    def save_duplicate_groups(self, crawl_id, groups): ...


class ResultsReadRepositoryPort(Protocol):
    def list_pages(self, query): ...
    def list_issues(self, query): ...
    def list_duplicate_groups(self, query): ...
    def get_page_detail(self, query): ...
    def find_recent_crawl(self): ...


class ExportPort(Protocol):
    def write_pages(self, target_path, rows): ...
    def write_issues(self, target_path, rows): ...


class ExportRepositoryPort(Protocol):
    def save_export(self, export_result): ...


class BackgroundExecutionPort(Protocol):
    def start(self, crawl_id, work): ...
    def request_stop(self, crawl_id): ...
    def is_running(self, crawl_id): ...
