"""Domain foundation for xseo."""

from xseo.domain.analysis import (
    DEFAULT_SEVERITY_POLICY,
    DEFAULT_THRESHOLDS,
    IssueAnalysisService,
    IssueSeverityPolicy,
    LinkStatusRecord,
    ThresholdPolicy,
    detect_cross_page_issues,
    detect_duplicate_meta_description_issues,
    detect_duplicate_title_issues,
    detect_link_issues,
    detect_page_issues,
    duplicate_group_key,
    issue_key,
    normalize_comparable_text,
)
from xseo.domain.crawler import (
    CrawlRunResult,
    NeverStopToken,
    StopToken,
    UrlCrawlEngine,
)
from xseo.domain.duplicates import detect_duplicate_groups
from xseo.domain.entities import (
    Crawl,
    CrawlConfig,
    DuplicateGroup,
    ExportResult,
    ExtractedPage,
    ExtractionResult,
    FetchResult,
    Heading,
    Issue,
    PageLink,
    Redirect,
    UrlRecord,
)
from xseo.domain.enums import (
    CrawlStatus,
    ExportKind,
    FetchStatus,
    HeadingLevel,
    IssueSeverity,
    IssueType,
    LinkRelation,
)
from xseo.domain.errors import (
    CrawlConfigErrorCode,
    CrawlStateErrorCode,
    DomainError,
    EventErrorCode,
    ExportErrorCode,
    IdErrorCode,
    UrlErrorCode,
)
from xseo.domain.extraction import (
    RawExtractedLink,
    SeoExtractionOutput,
    SeoExtractionPipeline,
    content_hash_for_text,
    extract_raw_links,
    normalize_visible_text,
    word_count,
)
from xseo.domain.frontier import (
    FrontierAddResult,
    FrontierAddStatus,
    FrontierAddSummary,
    FrontierEntry,
    FrontierEntryState,
    FrontierSnapshot,
    RejectedUrl,
    RejectionReason,
    UrlFrontier,
    UrlNormalizer,
)
from xseo.domain.ids import (
    CrawlId,
    DuplicateGroupId,
    ExportId,
    IssueId,
    PageId,
)
from xseo.domain.urls import BaseUrl, NormalizedUrl, RawUrl
from xseo.domain.validation import DomainValidationError, ValidationResult
from xseo.domain.value_objects import ContentHash, FilePath, WordCount

__all__ = [
    "BaseUrl",
    "ContentHash",
    "Crawl",
    "CrawlConfig",
    "CrawlConfigErrorCode",
    "CrawlId",
    "CrawlRunResult",
    "CrawlStateErrorCode",
    "CrawlStatus",
    "DEFAULT_SEVERITY_POLICY",
    "DEFAULT_THRESHOLDS",
    "DomainError",
    "DomainValidationError",
    "DuplicateGroup",
    "DuplicateGroupId",
    "EventErrorCode",
    "ExportErrorCode",
    "ExportId",
    "ExportKind",
    "ExportResult",
    "ExtractedPage",
    "ExtractionResult",
    "FetchResult",
    "FetchStatus",
    "FilePath",
    "FrontierAddResult",
    "FrontierAddStatus",
    "FrontierAddSummary",
    "FrontierEntry",
    "FrontierEntryState",
    "FrontierSnapshot",
    "Heading",
    "HeadingLevel",
    "IdErrorCode",
    "Issue",
    "IssueAnalysisService",
    "IssueId",
    "IssueSeverity",
    "IssueSeverityPolicy",
    "IssueType",
    "LinkRelation",
    "LinkStatusRecord",
    "NormalizedUrl",
    "NeverStopToken",
    "PageId",
    "PageLink",
    "RawUrl",
    "RawExtractedLink",
    "RejectedUrl",
    "RejectionReason",
    "Redirect",
    "SeoExtractionOutput",
    "SeoExtractionPipeline",
    "StopToken",
    "ThresholdPolicy",
    "UrlCrawlEngine",
    "UrlErrorCode",
    "UrlFrontier",
    "UrlNormalizer",
    "UrlRecord",
    "ValidationResult",
    "WordCount",
    "content_hash_for_text",
    "detect_cross_page_issues",
    "detect_duplicate_groups",
    "detect_duplicate_meta_description_issues",
    "detect_duplicate_title_issues",
    "detect_link_issues",
    "detect_page_issues",
    "extract_raw_links",
    "duplicate_group_key",
    "issue_key",
    "normalize_comparable_text",
    "normalize_visible_text",
    "word_count",
]
